import type { Metadata } from 'next';
import Link from 'next/link';
import SiteFooter from '@/components/SiteFooter';
import SiteHeader from '@/components/SiteHeader';
import { verificationLevels } from '@/lib/partner-verification';

export const metadata: Metadata = {
  title: 'Réseau partenaires installateurs',
  description: 'Rejoignez le réseau SafeR des techniciens et entreprises d’installation en Côte d’Ivoire.',
};

const matching = [
  ['40%', 'Compétences', 'Correspondance entre les certifications du partenaire et la mission.'],
  ['25%', 'Proximité', 'Zone d’intervention et temps de déplacement réaliste.'],
  ['15%', 'Disponibilité', 'Créneau confirmé avant toute affectation.'],
  ['10%', 'Qualité', 'Évaluations et incidents issus de missions terminées.'],
  ['10%', 'Niveau SafeR', 'Priorité maîtrisée aux profils Vérifiés et Certifiés.'],
];

export default function PartnersPage() {
  return <main className="theme-page bg-[#f3f5fb] text-black">
    <section className="relative overflow-hidden bg-black text-white"><div className="brand-grid absolute inset-0 opacity-35" /><SiteHeader /><div className="relative mx-auto grid min-h-[650px] max-w-7xl gap-12 px-5 pb-20 pt-12 lg:grid-cols-[1fr_.8fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-20"><div><p className="eyebrow">SafeR Partner Network</p><h1 className="mt-6 max-w-4xl text-5xl font-light leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Votre savoir-faire.<br /><span className="font-semibold text-[#52c6ff]">Notre standard de confiance.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">Techniciens, intégrateurs et entreprises d’installation : recevez des missions qualifiées, travaillez avec une documentation claire et construisez une réputation vérifiable.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/partenaires/inscription" className="rounded-full bg-[#4556f5] px-7 py-4 text-center text-sm font-bold text-white">Rejoindre le réseau</Link><Link href="/partenaires/tableau-de-bord" className="rounded-full border border-white/15 px-7 py-4 text-center text-sm font-bold">Mon espace partenaire</Link></div></div><div className="rounded-[34px] border border-white/12 bg-white/7 p-5 backdrop-blur"><div className="rounded-[28px] bg-[#111521] p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-white/55">Mission proposée</p><p className="mt-1 text-lg font-semibold">Installation villa · Riviera 4</p></div><span className="rounded-full bg-[#b8ff3d] px-3 py-1.5 text-[10px] font-bold text-black">MATCH 92%</span></div><div className="mt-10 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white/7 p-3"><p className="text-xl font-semibold">3</p><p className="mt-1 text-[10px] text-white/55">compétences</p></div><div className="rounded-2xl bg-white/7 p-3"><p className="text-xl font-semibold">8 km</p><p className="mt-1 text-[10px] text-white/55">distance</p></div><div className="rounded-2xl bg-white/7 p-3"><p className="text-xl font-semibold">4,8</p><p className="mt-1 text-[10px] text-white/55">qualité</p></div></div><div className="mt-3 rounded-2xl bg-[#4556f5] p-4"><p className="text-xs text-white/70">Votre niveau</p><p className="mt-1 font-semibold">Vérifié · priorité normale</p></div></div></div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="eyebrow">Trois niveaux lisibles</p><h2 className="section-title mt-5">La confiance se gagne.<br />Elle se vérifie dans le temps.</h2><p className="mt-6 max-w-2xl leading-7 text-black/55">Un badge n’est jamais acheté. Il résulte de preuves documentaires, d’un contrôle humain, de compétences démontrées et de la qualité observée sur le terrain.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{verificationLevels.map((level, index) => <article key={level.status} className={`rounded-[30px] border p-7 ${index === 2 ? 'border-transparent bg-black text-white' : 'border-black/8 bg-white'}`}><div className="flex items-center justify-between"><span className="text-sm font-semibold opacity-45">0{index + 1}</span><span className="verification-badge rounded-full px-3 py-1.5 text-[10px] font-bold text-black" style={{ backgroundColor: level.color }}>{level.label}</span></div><h3 className="mt-12 text-2xl font-semibold">{level.summary}</h3><ul className={`mt-7 space-y-3 text-sm leading-6 ${index === 2 ? 'text-white/70' : 'text-black/58'}`}>{level.criteria.map((criterion) => <li key={criterion} className="flex gap-3"><span style={{ color: level.color }}>✓</span><span>{criterion}</span></li>)}</ul></article>)}</div></div></section>

    <section className="bg-[#0b1d17] px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow text-[#b8ff3d]">Mise en relation équitable</p><h2 className="mt-5 text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl">Le meilleur profil pour chaque mission.</h2></div><p className="max-w-xl leading-7 text-white/65 lg:ml-auto">Le score aide à ordonner les propositions ; il ne remplace pas le choix humain. Les refus, disponibilités et contraintes de déplacement restent respectés.</p></div><div className="mt-14 grid gap-3 md:grid-cols-5">{matching.map(([weight, title, text]) => <article key={title} className="rounded-[24px] border border-white/10 p-5"><p className="text-3xl font-semibold text-[#b8ff3d]">{weight}</p><h3 className="mt-8 font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-white/55">{text}</p></article>)}</div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-8 rounded-[34px] bg-[#52c6ff] p-8 text-black lg:grid-cols-[1fr_auto] lg:items-center lg:p-12"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-black/55">Données minimales, contrôle maximal</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">Les documents KYC restent privés et chaque changement de statut est traçable.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-black/65">SafeR collecte uniquement les preuves nécessaires, limite les accès et prévoit rectification, retrait et revue humaine. Aucun refus définitif n’est prononcé par un score automatique.</p></div><Link href="/partenaires/inscription" className="rounded-full bg-black px-7 py-4 text-center text-sm font-bold text-white">Commencer mon dossier</Link></div></section>
    <SiteFooter />
  </main>;
}
