import type { Metadata } from 'next';
import Link from '@/components/Link';
import SiteFooter from '@/components/SiteFooter';
import SiteHeader from '@/components/SiteHeader';
import { getI18n, pageMetadata } from '@/lib/i18n/server';
import { verificationLevels } from '@/lib/partner-verification';

export async function generateMetadata(): Promise<Metadata> {
  const { d, locale } = await getI18n();
  return pageMetadata(d, locale, { title: d.partners.meta.title, description: d.partners.meta.description, path: '/partenaires' });
}

export default async function PartnersPage() {
  const { d } = await getI18n();
  const p = d.partners;
  const levels = verificationLevels(d);
  return <main id="contenu" className="theme-page bg-[#f3f5fb] text-black">
    <section className="relative overflow-hidden bg-black text-white"><div className="brand-grid absolute inset-0 opacity-35" /><SiteHeader /><div className="relative mx-auto grid min-h-[650px] max-w-7xl gap-12 px-5 pb-20 pt-12 lg:grid-cols-[1fr_.8fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-20"><div><p className="eyebrow">{p.hero.eyebrow}</p><h1 className="mt-6 max-w-4xl text-5xl font-light leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">{p.hero.title1}<br /><span className="font-semibold text-[#52c6ff]">{p.hero.title2}</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">{p.hero.intro}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/partenaires/inscription" className="rounded-full bg-[#4556f5] px-7 py-4 text-center text-sm font-bold text-white">{p.hero.join}</Link><Link href="/partenaires/tableau-de-bord" className="rounded-full border border-white/15 px-7 py-4 text-center text-sm font-bold">{p.hero.dashboard}</Link></div></div><div className="rounded-[34px] border border-white/12 bg-white/7 p-5 backdrop-blur"><div className="rounded-[28px] bg-[#111521] p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-white/55">{p.hero.mock.mission}</p><p className="mt-1 text-lg font-semibold">{p.hero.mock.title}</p></div><span className="rounded-full bg-[#b8ff3d] px-3 py-1.5 text-[10px] font-bold text-black">{p.hero.mock.match}</span></div><div className="mt-10 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white/7 p-3"><p className="text-xl font-semibold">3</p><p className="mt-1 text-[10px] text-white/55">{p.hero.mock.skills}</p></div><div className="rounded-2xl bg-white/7 p-3"><p className="text-xl font-semibold">8 km</p><p className="mt-1 text-[10px] text-white/55">{p.hero.mock.distance}</p></div><div className="rounded-2xl bg-white/7 p-3"><p className="text-xl font-semibold">4,8</p><p className="mt-1 text-[10px] text-white/55">{p.hero.mock.quality}</p></div></div><div className="mt-3 rounded-2xl bg-[#4556f5] p-4"><p className="text-xs text-white/70">{p.hero.mock.level}</p><p className="mt-1 font-semibold">{p.hero.mock.levelValue}</p></div></div></div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="eyebrow">{p.levels.eyebrow}</p><h2 className="section-title mt-5">{p.levels.title1}<br />{p.levels.title2}</h2><p className="mt-6 max-w-2xl leading-7 text-black/55">{p.levels.intro}</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{levels.map((level, index) => <article key={level.status} className={`flex flex-col rounded-[30px] border p-7 ${index === 2 ? 'border-transparent bg-black text-white' : 'border-black/8 bg-white'}`}><div className="flex items-center justify-between"><span className="text-sm font-semibold opacity-45">0{index + 1}</span><span className="verification-badge rounded-full px-3 py-1.5 text-[10px] font-bold text-black" style={{ backgroundColor: level.color }}>{level.label}</span></div><h3 className="mt-12 text-2xl font-semibold">{level.summary}</h3><ul className={`mt-7 space-y-3 text-sm leading-6 ${index === 2 ? 'text-white/70' : 'text-black/58'}`}>{level.criteria.map((criterion) => <li key={criterion} className="flex gap-3"><span style={{ color: level.color }}>✓</span><span>{criterion}</span></li>)}</ul><Link href={`/partenaires/niveaux/${level.status}`} className={`mt-auto pt-8 text-xs font-bold underline underline-offset-4 ${index === 2 ? 'text-[#52c6ff]' : 'text-[#4556f5]'}`}>{p.levels.viewLevel} →</Link></article>)}</div></div></section>

    <section className="bg-[#0b1d17] px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow text-[#b8ff3d]">{p.matching.eyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl">{p.matching.title}</h2></div><p className="max-w-xl leading-7 text-white/65 lg:ml-auto">{p.matching.intro}</p></div><div className="mt-14 grid gap-3 md:grid-cols-5">{p.matching.items.map(([weight, title, text]) => <article key={title} className="rounded-[24px] border border-white/10 p-5"><p className="text-3xl font-semibold text-[#b8ff3d]">{weight}</p><h3 className="mt-8 font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-white/55">{text}</p></article>)}</div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-8 rounded-[34px] bg-[#52c6ff] p-8 text-black lg:grid-cols-[1fr_auto] lg:items-center lg:p-12"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-black/55">{p.privacy.eyebrow}</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">{p.privacy.title}</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-black/65">{p.privacy.text}</p><Link href="/partenaires/code-de-conduite" className="mt-5 inline-flex text-sm font-bold underline underline-offset-4">{p.codeLink} →</Link></div><Link href="/partenaires/inscription" className="rounded-full bg-black px-7 py-4 text-center text-sm font-bold text-white">{p.privacy.cta}</Link></div></section>
    <SiteFooter />
  </main>;
}
