import type { Metadata } from 'next';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';

export const metadata: Metadata = { title: 'Quartier intelligent & Smart City | SafeR', description: 'SafeR Collective relie sécurité, accès, supervision et données utiles pour les résidences, quartiers et villes de Côte d’Ivoire.' };

const pillars = [
  ['01', 'Accès unifiés', 'Résidents, visiteurs, prestataires et véhicules gérés depuis un même référentiel.'],
  ['02', 'Supervision intelligente', 'Vidéo, alarmes et incidents centralisés pour voir plus vite et décider plus juste.'],
  ['03', 'Patrouilles coordonnées', 'Missions, rondes et escalades tracées en temps réel.'],
  ['04', 'Communication résidents', 'Alertes vérifiées, consignes et bouton SOS dans une application commune.'],
];

export default function DistrictsPage() {
  return <main className="theme-page districts-page bg-[#eff3f0] text-[#0a1814]">
    <section className="relative min-h-[90vh] overflow-hidden bg-[#07120f] text-white"><SiteHeader /><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(184,255,61,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(184,255,61,.12)_1px,transparent_1px)] [background-size:52px_52px]" /><div className="absolute -right-48 top-16 size-[650px] rounded-full bg-[#0ca678]/20 blur-[120px]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pt-24"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b8ff3d]">SafeR Collective</p><h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Quand chaque espace veille sur l’autre.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/55">Une plateforme de sûreté partagée pour résidences, quartiers, campus, zones commerciales et collectivités.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#projet" className="rounded-full bg-[#b8ff3d] px-7 py-4 text-center text-sm font-bold text-[#07120f]">Étudier mon projet</a><a href="#architecture" className="rounded-full border border-white/15 px-7 py-4 text-center text-sm font-bold">Voir l’architecture</a></div></div><div className="rounded-[32px] border border-white/12 bg-white/6 p-5 backdrop-blur"><div className="rounded-[25px] bg-[#12261f] p-5"><div className="flex justify-between"><div><p className="text-xs text-white/35">Centre opérationnel</p><p className="mt-1 font-semibold">Zone Riviera Connectée</p></div><span className="rounded-full bg-[#b8ff3d] px-3 py-1.5 text-[10px] font-bold text-[#07120f]">EN LIGNE</span></div><div className="mt-12 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/7 p-4"><p className="text-3xl font-semibold">98.7%</p><p className="mt-2 text-xs text-white/35">Disponibilité réseau</p></div><div className="rounded-2xl bg-white/7 p-4"><p className="text-3xl font-semibold">42</p><p className="mt-2 text-xs text-white/35">Points supervisés</p></div><div className="col-span-2 rounded-2xl bg-[#b8ff3d] p-4 text-[#07120f]"><p className="text-xs text-black/45">Situation en cours</p><div className="mt-3 flex items-center justify-between"><p className="font-semibold">Aucun incident critique</p><span className="grid size-9 place-items-center rounded-full bg-[#07120f] text-white">✓</span></div></div></div></div></div></div></section>

    <section id="architecture" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-2 lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#659413]">Une sécurité collective, enfin lisible</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl lg:text-6xl">Du portail au centre de supervision.</h2></div><p className="max-w-lg leading-7 text-black/50 lg:ml-auto">SafeR Collective crée un fil opérationnel unique entre les équipements, les équipes terrain, les responsables et les résidents.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2">{pillars.map(([n,title,text],i)=><article key={n} className={`rounded-[28px] p-7 ${i===0?'bg-[#b8ff3d]':'bg-white border border-black/8'}`}><div className="flex justify-between"><span className="text-sm text-black/35">{n}</span><span className="text-2xl">{['↗','◉','⌁','✦'][i]}</span></div><h3 className="mt-16 text-2xl font-semibold">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-black/50">{text}</p></article>)}</div></div></section>

    <section className="bg-[#0b1d17] px-5 py-24 text-white lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b8ff3d]">Le bon niveau d’information, au bon rôle</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl lg:text-6xl">Une expérience pour chaque acteur.</h2></div><div className="mt-14 grid gap-4 lg:grid-cols-3"><div className="rounded-[28px] border border-white/10 p-7"><span className="text-3xl">◎</span><h3 className="mt-12 text-2xl font-semibold">Résidents</h3><p className="mt-3 text-sm leading-6 text-white/45">Invitations, alertes, SOS, consignes et suivi depuis l’application SafeR.</p></div><div className="rounded-[28px] bg-[#b8ff3d] p-7 text-[#07120f]"><span className="text-3xl">◈</span><h3 className="mt-12 text-2xl font-semibold">Équipes de sécurité</h3><p className="mt-3 text-sm leading-6 text-black/50">Poste de garde, événements, rondes et procédures réunis dans un tableau de bord opérationnel.</p></div><div className="rounded-[28px] border border-white/10 p-7"><span className="text-3xl">▦</span><h3 className="mt-12 text-2xl font-semibold">Gestionnaires</h3><p className="mt-3 text-sm leading-6 text-white/45">Indicateurs, incidents, qualité de service et budgets pour piloter avec des faits.</p></div></div></div></section>

    <section id="smart-city" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[460px] overflow-hidden rounded-[34px] bg-[#cfe7df] p-7"><div className="absolute inset-0 opacity-45 [background-image:radial-gradient(#285848_1.5px,transparent_1.5px)] [background-size:24px_24px]" /><div className="relative grid h-full content-between gap-32"><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-[.14em] text-black/45">Vue territoire</p><span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold">Abidjan · Démo</span></div><div className="grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white/85 p-4"><p className="text-2xl font-semibold">08</p><p className="mt-1 text-xs text-black/40">Zones actives</p></div><div className="rounded-2xl bg-[#0b1d17] p-4 text-white"><p className="text-2xl font-semibold">214</p><p className="mt-1 text-xs text-white/40">Capteurs</p></div><div className="rounded-2xl bg-[#b8ff3d] p-4"><p className="text-2xl font-semibold">99%</p><p className="mt-1 text-xs text-black/40">Opérationnel</p></div></div></div></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#659413]">SafeR Smart City</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl">Mieux comprendre la ville pour mieux la protéger.</h2><p className="mt-6 leading-7 text-black/50">Une couche numérique interopérable pour relier sûreté urbaine, flux, incidents, infrastructures et coordination des équipes.</p><ul className="mt-8 space-y-4 text-sm"><li className="flex gap-3"><span className="text-[#659413]">✓</span>Hypervision multi-sites et cartographie opérationnelle</li><li className="flex gap-3"><span className="text-[#659413]">✓</span>Analyse des tendances et maintenance préventive</li><li className="flex gap-3"><span className="text-[#659413]">✓</span>Gouvernance des accès, rôles et données</li><li className="flex gap-3"><span className="text-[#659413]">✓</span>Intégration progressive aux systèmes existants</li></ul></div></div></section>

    <section id="projet" className="bg-[#b8ff3d] px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-black/45">Parlons de votre zone</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl">Construisons votre architecture SafeR.</h2><p className="mt-5 max-w-md text-sm leading-6 text-black/55">Un expert vous recontacte pour cadrer les sites, les acteurs et le niveau de service attendu.</p></div><form className="grid gap-4 rounded-[30px] bg-white p-6 sm:grid-cols-2 sm:p-8"><label className="text-sm font-semibold">Nom et prénom<input className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f5f7f5] px-4 py-3.5 font-normal outline-none" placeholder="Votre nom" /></label><label className="text-sm font-semibold">Organisation<input className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f5f7f5] px-4 py-3.5 font-normal outline-none" placeholder="Résidence, entreprise, commune…" /></label><label className="text-sm font-semibold">Téléphone<input className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f5f7f5] px-4 py-3.5 font-normal outline-none" placeholder="+225 00 00 00 00 00" /></label><label className="text-sm font-semibold">Type de projet<select className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f5f7f5] px-4 py-3.5 font-normal outline-none"><option>Résidence / copropriété</option><option>Quartier</option><option>Campus / zone d’activité</option><option>Collectivité / ville</option></select></label><label className="text-sm font-semibold sm:col-span-2">Votre besoin<textarea className="mt-2 min-h-24 w-full rounded-2xl border border-black/10 bg-[#f5f7f5] px-4 py-3.5 font-normal outline-none" placeholder="Nombre d’accès, taille de la zone, enjeux principaux…" /></label><button type="button" className="rounded-full bg-[#07120f] px-6 py-4 text-sm font-bold text-white sm:col-span-2">Être rappelé par un expert</button></form></div></section>
    <SiteFooter />
  </main>;
}
