import type { Metadata } from 'next';
import Link from '@/components/Link';
import LeadForm from '@/components/LeadForm';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
import Icon, { GlyphIcon, type IconName } from '@/components/Icon';
import { segmentIcons, segmentOrder } from '@/lib/collective';
import { getI18n, pageMetadata } from '@/lib/i18n/server';

export async function generateMetadata(): Promise<Metadata> {
  const { d, locale } = await getI18n();
  return pageMetadata(d, locale, { title: d.collective.meta.title, description: d.collective.meta.description, path: '/quartiers' });
}

export default async function DistrictsPage() {
  const { d } = await getI18n();
  const c = d.collective;
  return <main id="contenu" className="theme-page districts-page bg-[#eff3f0] text-[#0a1814]">
    <section className="relative min-h-[90vh] overflow-hidden bg-[#07120f] text-white"><SiteHeader /><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(184,255,61,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(184,255,61,.12)_1px,transparent_1px)] [background-size:52px_52px]" /><div className="absolute -right-48 top-16 size-[650px] rounded-full bg-[#0ca678]/20 blur-[120px]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pt-24"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b8ff3d]">{c.hero.eyebrow}</p><h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">{c.hero.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/55">{c.hero.intro}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#projet" className="rounded-full bg-[#b8ff3d] px-7 py-4 text-center text-sm font-bold text-[#07120f]">{c.hero.study}</a><a href="#architecture" className="rounded-full border border-white/15 px-7 py-4 text-center text-sm font-bold">{c.hero.architecture}</a></div></div><div className="rounded-[32px] border border-white/12 bg-white/6 p-5 backdrop-blur"><div className="rounded-[25px] bg-[#12261f] p-5"><div className="flex justify-between"><div><p className="text-xs text-white/35">{c.hero.mock.center}</p><p className="mt-1 font-semibold">{c.hero.mock.zone}</p></div><span className="rounded-full bg-[#b8ff3d] px-3 py-1.5 text-[10px] font-bold text-[#07120f]">{c.hero.mock.online}</span></div><div className="mt-12 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/7 p-4"><p className="text-3xl font-semibold">98.7%</p><p className="mt-2 text-xs text-white/35">{c.hero.mock.uptime}</p></div><div className="rounded-2xl bg-white/7 p-4"><p className="text-3xl font-semibold">42</p><p className="mt-2 text-xs text-white/35">{c.hero.mock.points}</p></div><div className="col-span-2 rounded-2xl bg-[#b8ff3d] p-4 text-[#07120f]"><p className="text-xs text-black/45">{c.hero.mock.situation}</p><div className="mt-3 flex items-center justify-between"><p className="font-semibold">{c.hero.mock.noIncident}</p><span className="grid size-9 place-items-center rounded-full bg-[#07120f] text-white">✓</span></div></div></div></div></div></div></section>

    <section className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-2 lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#659413]">{c.segmentsEyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl lg:text-6xl">{c.segmentsTitle}</h2></div></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{segmentOrder.map((id, i) => { const seg = c.segments[id]; return <Link key={id} href={`/quartiers/${id}`} data-reveal="" data-reveal-delay={String(i)} className={`group card-lift flex min-h-[300px] flex-col rounded-[28px] p-7 ${i === 0 ? 'bg-[#b8ff3d]' : 'border border-black/8 bg-white'}`}><div className="flex justify-between"><span className="grid size-11 place-items-center rounded-full bg-black/5"><GlyphIcon glyph={segmentIcons[id]} size={22} /></span><span className="grid size-10 place-items-center rounded-full border border-current/15 transition group-hover:translate-x-1">→</span></div><h3 className="mt-auto text-2xl font-semibold">{seg.title}</h3><p className="mt-3 text-sm leading-6 text-black/55">{seg.summary}</p></Link>; })}</div></div></section>

    <section id="architecture" className="bg-white px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-2 lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#659413]">{c.architecture.eyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl lg:text-6xl">{c.architecture.title}</h2></div><p className="max-w-lg leading-7 text-black/50 lg:ml-auto">{c.architecture.intro}</p></div><div className="mt-14 grid gap-4 md:grid-cols-2">{c.architecture.pillars.map(([n, title, text], i) => <article key={n} className={`rounded-[28px] p-7 ${i === 0 ? 'bg-[#b8ff3d]' : 'bg-[#eff3f0] border border-black/8'}`}><div className="flex justify-between"><span className="text-sm text-black/35">{n}</span><Icon name={(['users', 'eye', 'map', 'message'] as IconName[])[i]} size={26} /></div><h3 className="mt-16 text-2xl font-semibold">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-black/50">{text}</p></article>)}</div></div></section>

    <section className="bg-[#0b1d17] px-5 py-24 text-white lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b8ff3d]">{c.roles.eyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl lg:text-6xl">{c.roles.title}</h2></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{c.roles.items.map(([icon, title, text], i) => <div key={title} className={`rounded-[28px] p-7 ${i === 1 ? 'bg-[#b8ff3d] text-[#07120f]' : 'border border-white/10'}`}><GlyphIcon glyph={icon} size={30} /><h3 className="mt-12 text-2xl font-semibold">{title}</h3><p className={`mt-3 text-sm leading-6 ${i === 1 ? 'text-black/50' : 'text-white/45'}`}>{text}</p></div>)}</div></div></section>

    <section id="smart-city" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[460px] overflow-hidden rounded-[34px] bg-[#cfe7df] p-7"><div className="absolute inset-0 opacity-45 [background-image:radial-gradient(#285848_1.5px,transparent_1.5px)] [background-size:24px_24px]" /><div className="relative grid h-full content-between gap-32"><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-[.14em] text-black/45">{c.smartCity.mock.territory}</p><span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold">{c.smartCity.mock.demo}</span></div><div className="grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white/85 p-4"><p className="text-2xl font-semibold">08</p><p className="mt-1 text-xs text-black/40">{c.smartCity.mock.zones}</p></div><div className="rounded-2xl bg-[#0b1d17] p-4 text-white"><p className="text-2xl font-semibold">214</p><p className="mt-1 text-xs text-white/40">{c.smartCity.mock.sensors}</p></div><div className="rounded-2xl bg-[#b8ff3d] p-4"><p className="text-2xl font-semibold">99%</p><p className="mt-1 text-xs text-black/40">{c.smartCity.mock.operational}</p></div></div></div></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#659413]">{c.smartCity.eyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl">{c.smartCity.title}</h2><p className="mt-6 leading-7 text-black/50">{c.smartCity.intro}</p><ul className="mt-8 space-y-4 text-sm">{c.smartCity.bullets.map((b) => <li key={b} className="flex gap-3"><span className="text-[#659413]">✓</span>{b}</li>)}</ul><Link href="/quartiers/collectivites" className="mt-8 inline-flex rounded-full bg-[#0b1d17] px-6 py-3.5 text-sm font-bold text-white">{c.viewSegment} →</Link></div></div></section>

    <section id="projet" className="bg-[#b8ff3d] px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-black/45">{c.project.eyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-5xl">{c.project.title}</h2><p className="mt-5 max-w-md text-sm leading-6 text-black/55">{c.project.intro}</p></div><LeadForm type="project" className="rounded-[30px] bg-white p-6 sm:p-8" submitLabel={c.project.submit} consentLabel={c.project.consent} fields={[{ name: 'name', label: c.project.name, placeholder: c.project.namePlaceholder, required: true }, { name: 'organization', label: c.project.organization, placeholder: c.project.organizationPlaceholder }, { name: 'phone', label: c.project.phone, placeholder: c.project.phonePlaceholder, required: true }, { name: 'email', label: c.project.email, placeholder: c.project.emailPlaceholder }, { name: 'projectType', label: c.project.type, options: c.project.types, span: true }, { name: 'message', label: c.project.need, placeholder: c.project.needPlaceholder }]} /></div></section>
    <SiteFooter />
  </main>;
}
