import type { Metadata } from 'next';
import Link from 'next/link';
import { requireChatGPTUser } from '@/app/chatgpt-auth';
import SiteFooter from '@/components/SiteFooter';
import SiteHeader from '@/components/SiteHeader';
import { countPartnerDocuments, getPartnerByUserId } from '@/lib/partner-db';
import { verificationLevels } from '@/lib/partner-verification';

export const metadata: Metadata = { title: 'Espace partenaire', description: 'Suivez votre vérification et vos missions SafeR.' };
export const dynamic = 'force-dynamic';

export default async function PartnerDashboardPage() {
  const user = await requireChatGPTUser('/partenaires/tableau-de-bord');
  const partner = await getPartnerByUserId(user.id);
  const documentCount = partner ? await countPartnerDocuments(partner.id) : 0;
  const level = verificationLevels.find((item) => item.status === partner?.verification_status) || verificationLevels[0];
  const skills = partner ? JSON.parse(partner.skills_json) as string[] : [];

  return <main className="theme-page bg-[#f3f5fb] text-black">
    <section className="bg-black text-white"><SiteHeader /><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 pb-14 pt-8 sm:flex-row sm:items-end sm:justify-between lg:px-8"><div><p className="eyebrow">Espace partenaire</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Bonjour, {user.name}.</h1><p className="mt-3 text-sm text-white/60">{user.email}</p></div><a href="/signout-with-chatgpt?return_to=/partenaires" className="rounded-full border border-white/15 px-5 py-3 text-center text-xs font-bold">Se déconnecter</a></div></section>
    {!partner ? <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-4xl rounded-[34px] border border-black/8 bg-white p-8 text-center sm:p-14"><span className="mx-auto grid size-16 place-items-center rounded-full bg-[#e7f7ff] text-2xl">◎</span><h2 className="mt-6 text-3xl font-semibold">Votre profil partenaire n’est pas encore créé.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-black/55">Déposez votre candidature pour recevoir votre statut initial et démarrer le parcours de vérification.</p><Link href="/partenaires/inscription" className="mt-7 inline-flex rounded-full bg-[#4556f5] px-7 py-4 text-sm font-bold text-white">Créer mon profil</Link></div></section> : <>
      <section className="px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-[32px] bg-[#4556f5] p-7 text-white sm:p-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-white/90">Statut actuel</p><h2 className="mt-5 text-4xl font-semibold">{level.label}</h2></div><span className="verification-badge rounded-full px-4 py-2 text-xs font-bold text-black" style={{ backgroundColor: level.color }}>{partner.application_stage.replaceAll('_', ' ')}</span></div><p className="mt-5 max-w-xl leading-7 text-white/90">{level.summary}</p><div className="mt-9 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-semibold">{documentCount}</p><p className="mt-1 text-[10px] text-white/70">document(s)</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-semibold">{partner.technical_score}%</p><p className="mt-1 text-[10px] text-white/70">test technique</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-semibold">{partner.completed_missions}</p><p className="mt-1 text-[10px] text-white/70">missions</p></div></div></article><article className="rounded-[32px] border border-black/8 bg-white p-7 sm:p-9"><p className="eyebrow">Prochaine étape</p><h2 className="mt-5 text-2xl font-semibold">{documentCount ? 'Revue KYC en préparation' : 'Déposer une preuve KYC'}</h2><p className="mt-4 text-sm leading-6 text-black/55">{documentCount ? 'Un contrôleur habilité vérifiera l’authenticité, la cohérence et l’appartenance du document avant tout changement de statut.' : 'Complétez votre dossier avec un document PDF, JPG ou PNG depuis le formulaire sécurisé.'}</p><Link href="/partenaires/inscription" className="mt-7 inline-flex rounded-full bg-black px-6 py-3.5 text-sm font-bold text-white">Mettre à jour mon dossier</Link></article></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-[30px] border border-black/8 bg-white p-7"><p className="eyebrow">Votre profil</p><dl className="mt-6 space-y-4 text-sm"><div className="flex justify-between gap-4 border-b border-black/8 pb-4"><dt className="text-black/48">Nom légal</dt><dd className="font-semibold">{partner.legal_name}</dd></div><div className="flex justify-between gap-4 border-b border-black/8 pb-4"><dt className="text-black/48">Zone principale</dt><dd className="font-semibold">{partner.commune}</dd></div><div className="flex justify-between gap-4"><dt className="text-black/48">Compétences</dt><dd className="max-w-[65%] text-right font-semibold">{skills.join(', ')}</dd></div></dl></article><article className="rounded-[30px] bg-[#0b1d17] p-7 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b8ff3d]">Missions proposées</p><h2 className="mt-4 text-2xl font-semibold">Aucune mission en attente.</h2></div><span className="text-3xl">⌁</span></div><p className="mt-5 max-w-xl text-sm leading-6 text-white/60">Dès que votre niveau et vos compétences correspondent à un besoin, la mission apparaît ici avec lieu, créneau, rémunération et score de correspondance. Vous restez libre d’accepter ou refuser.</p></article></div></div></section>
    </>}
    <SiteFooter />
  </main>;
}
