import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';

export const metadata: Metadata = { title: 'À propos', description: 'SafeR, marque de RADIANT ASSISTANCE SECURITY, développe une sécurité intelligente pensée pour la Côte d’Ivoire.' };

export default function AboutPage() {
  return <main className="theme-page bg-[#f3f5fb] text-black">
    <section className="relative min-h-[82vh] overflow-hidden bg-black text-white"><img src="https://images.pexels.com/photos/30692441/pexels-photo-30692441/free-photo-of-security-officer-in-dark-control-room-with-monitors.jpeg?auto=compress&dpr=1&h=1100&w=1800" alt="Centre de supervision de sécurité" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-r from-black via-black/85 to-[#4556f5]/20" /><SiteHeader /><div className="relative mx-auto flex min-h-[calc(82vh-96px)] max-w-7xl items-end px-5 pb-20 lg:px-8"><div className="max-w-5xl"><p data-i18n="about.eyebrow" className="text-xs font-bold uppercase tracking-[.16em] text-[#52c6ff]">À propos de SafeR</p><h1 data-i18n="about.title" className="mt-6 text-5xl font-light leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-7xl">La confiance inspire tout ce que nous protégeons.</h1><p data-i18n="about.intro" className="mt-7 max-w-2xl text-lg leading-8 text-white/60">SafeR est la marque de sécurité intelligente de RADIANT ASSISTANCE SECURITY, conçue pour rapprocher technologie, présence humaine et qualité de service.</p></div></div></section>
    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Notre ambition</p><h2 className="section-title mt-5">Digitaliser la sérénité, sans déshumaniser la sécurité.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[['100%','Parcours client digitalisé'],['24/7','Veille et assistance'],['03','Échelles : maison, quartier, ville'],['CI','Conçu pour le contexte ivoirien']].map(([value,label], index) => <article key={label} className={`rounded-[28px] p-7 ${index===0?'bg-[#4556f5] text-white':'border border-black/8 bg-white'}`}><p className="text-4xl font-light">{value}</p><p className={`mt-10 text-sm ${index===0?'text-white/60':'text-black/50'}`}>{label}</p></article>)}</div></div></section>
    <section className="bg-black px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#52c6ff]">Nos principes</p><h2 className="mt-5 text-4xl font-light">La protection comme expérience de confiance.</h2></div>{[['Clarté','Des offres, alertes et décisions compréhensibles.'],['Continuité','Un parcours suivi de la découverte à la maintenance.']].map(([title,text]) => <article key={title} className="border-l border-white/15 pl-7"><h3 className="text-2xl font-semibold">{title}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-white/50">{text}</p></article>)}</div></section>
    <section className="bg-[#4556f5] px-5 py-20 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><h2 className="max-w-3xl text-4xl font-light">Découvrez la protection qui correspond à votre espace.</h2><Link href="/diagnostic" data-i18n="common.assessment" className="rounded-full bg-black px-7 py-4 text-center text-sm font-bold text-white">Faire mon diagnostic</Link></div></section>
    <SiteFooter />
  </main>;
}
