import type { Metadata } from 'next';
import Link from '@/components/Link';
import SiteHeader from '@/components/SiteHeader';
import { formatDate, getI18n, pageMetadata } from '@/lib/i18n/server';
import { CONTACT_PHONE_HREF } from '@/lib/site';

export async function generateMetadata(): Promise<Metadata> {
  const { d, locale } = await getI18n();
  return { ...pageMetadata(d, locale, { title: d.client.meta.title, description: d.client.meta.description, path: '/espace-client' }), robots: { index: false } };
}

export default async function ClientPage() {
  const { d, locale } = await getI18n();
  const c = d.client;
  const today = formatDate(new Date(), locale, { weekday: 'long', day: 'numeric', month: 'long' });
  return <main id="contenu" className="theme-page client-page min-h-screen bg-[#e9eeea] text-[#0a1814]"><SiteHeader dark={false} />
    <div className="mx-auto max-w-[1440px] px-4 pb-10 pt-4 sm:px-6 lg:px-8"><div className="grid gap-5 lg:grid-cols-[240px_1fr]">
      <aside className="hidden h-[calc(100vh-120px)] rounded-[26px] bg-[#0b1d17] p-5 text-white lg:flex lg:flex-col lg:sticky lg:top-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b8ff3d]">{c.aside.title}</p><div className="mt-6 space-y-1 text-sm"><a className="flex items-center gap-3 rounded-xl bg-white/10 px-3 py-3" href="#contenu"><span>⌂</span>{c.aside.overview}</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#monitoring"><span>◉</span>{c.aside.monitoring}</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#installation"><span>↗</span>{c.aside.installation}</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#payments"><span>▤</span>{c.aside.payments}</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#support"><span>✦</span>{c.aside.support}</a></div></div><div className="mt-auto rounded-2xl bg-[#b8ff3d] p-4 text-[#07120f]"><p className="text-xs font-bold">{c.aside.assistance}</p><p className="mt-1 text-xs text-black/50">{c.aside.doubt}</p><Link href="/support/contact" className="mt-4 block w-full rounded-full bg-[#07120f] px-4 py-2.5 text-center text-xs font-bold text-white">{c.aside.contact}</Link></div></aside>
      <section>
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm capitalize text-black/40">{today}</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.035em]">{c.greeting}</h1></div><div className="flex items-center gap-3"><button type="button" className="rounded-full border border-black/10 bg-white px-4 py-2.5 text-sm font-semibold">{c.documents}</button><span className="grid size-11 place-items-center rounded-full bg-[#b8ff3d] text-sm font-bold">{c.initials}</span></div></div>
        <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
          <div id="monitoring" className="relative overflow-hidden rounded-[30px] bg-[#0b1d17] p-6 text-white sm:p-8"><div className="absolute -right-10 -top-20 size-72 rounded-full bg-[#b8ff3d]/12 blur-3xl" /><div className="relative flex items-start justify-between"><div><p className="text-xs text-white/40">{c.monitoring.residence}</p><h2 className="mt-2 text-2xl font-semibold">{c.monitoring.protected}</h2></div><span className="grid size-12 place-items-center rounded-full bg-[#b8ff3d] text-xl text-[#07120f]">✓</span></div><div className="relative mt-12 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">04</p><p className="mt-1 text-xs text-white/35">{c.monitoring.access}</p></div><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">07</p><p className="mt-1 text-xs text-white/35">{c.monitoring.cameras}</p></div><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">06</p><p className="mt-1 text-xs text-white/35">{c.monitoring.sensors}</p></div><div className="rounded-2xl bg-[#b8ff3d] p-4 text-[#07120f]"><p className="text-2xl font-semibold">24/7</p><p className="mt-1 text-xs text-black/40">{c.monitoring.watch}</p></div></div><div className="relative mt-5 flex flex-wrap gap-3"><button type="button" className="rounded-full bg-white px-5 py-3 text-xs font-bold text-[#07120f]">{c.monitoring.arm}</button><button type="button" className="rounded-full border border-white/12 px-5 py-3 text-xs font-bold">{c.monitoring.viewCameras}</button><button type="button" className="rounded-full border border-white/12 px-5 py-3 text-xs font-bold">{c.monitoring.openGate}</button></div></div>
          <div id="installation" className="rounded-[30px] bg-white p-6"><div className="flex items-start justify-between"><div><p className="text-xs text-black/40">{c.installation.project}</p><h2 className="mt-1 text-xl font-semibold">{c.installation.title}</h2></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-[10px] font-bold text-amber-700">{c.installation.status}</span></div><div className="mt-7 space-y-5"><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#b8ff3d] text-xs">✓</span><div><p className="text-sm font-semibold">{c.installation.quoteSigned}</p></div></div><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#b8ff3d] text-xs">✓</span><div><p className="text-sm font-semibold">{c.installation.deposit}</p><p className="mt-1 text-xs text-black/35">{c.installation.depositVia}</p></div></div><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full border-4 border-[#b8ff3d] text-xs" /><div><p className="text-sm font-semibold">{c.installation.planned}</p></div></div><div className="flex gap-3 opacity-35"><span className="grid size-7 shrink-0 place-items-center rounded-full border border-black/20 text-xs" /><div><p className="text-sm font-semibold">{c.installation.commissioning}</p><p className="mt-1 text-xs">{c.installation.upcoming}</p></div></div></div><button type="button" className="mt-6 w-full rounded-full border border-black/10 px-4 py-3 text-xs font-bold">{c.installation.modify}</button></div>
        </div>
        <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">
          <article className="rounded-[26px] bg-white p-6"><div className="flex justify-between"><div><p className="text-xs text-black/40">{c.event.title}</p><h3 className="mt-1 font-semibold">{c.event.gate}</h3></div><span className="grid size-10 place-items-center rounded-full bg-[#e9eeea]">↗</span></div><div className="mt-8 border-l-2 border-[#b8ff3d] pl-4"><p className="text-sm font-semibold">{c.event.authorized}</p><p className="mt-1 text-xs text-black/35">{c.event.by}</p></div><button type="button" className="mt-6 text-xs font-bold underline underline-offset-4">{c.event.log}</button></article>
          <article id="payments" className="rounded-[26px] bg-white p-6"><div className="flex justify-between"><div><p className="text-xs text-black/40">{c.payment.title}</p><h3 className="mt-1 font-semibold">{c.payment.plan}</h3></div><span className="grid size-10 place-items-center rounded-full bg-[#e9eeea]">▤</span></div><p className="mt-8 text-3xl font-semibold">34 900 <span className="text-sm">{d.common.fcfa}</span></p><p className="mt-1 text-xs text-black/35">{c.payment.due}</p><button type="button" className="mt-6 rounded-full border border-black/10 px-4 py-2.5 text-xs font-bold">{c.payment.manage}</button></article>
          <article id="support" className="rounded-[26px] bg-[#b8ff3d] p-6 md:col-span-2 xl:col-span-1"><div className="flex justify-between"><div><p className="text-xs text-black/40">{c.maintenance.title}</p><h3 className="mt-1 font-semibold">{c.maintenance.check}</h3></div><span className="grid size-10 place-items-center rounded-full bg-white">✦</span></div><p className="mt-8 text-sm leading-6 text-black/55">{c.maintenance.text}</p><Link href="/support/maintenance" className="mt-6 inline-flex rounded-full bg-[#07120f] px-4 py-2.5 text-xs font-bold text-white">{c.maintenance.book}</Link></article>
        </div>
        <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-[30px] bg-white p-6 sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#669516]">{c.upsell.eyebrow}</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">{c.upsell.title}</h2><p className="mt-2 max-w-lg text-sm leading-6 text-black/45">{c.upsell.text}</p></div><span className="grid size-14 place-items-center rounded-2xl bg-[#e9eeea] text-2xl">◉</span></div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/store/video/cameras-exterieures" className="rounded-full bg-[#0b1d17] px-5 py-3 text-center text-xs font-bold text-white">{c.upsell.add}</Link><button type="button" className="rounded-full border border-black/10 px-5 py-3 text-xs font-bold">{c.upsell.later}</button></div></article><article className="rounded-[30px] border border-black/8 p-6"><p className="text-xs text-black/40">{c.help.title}</p><h2 className="mt-2 text-xl font-semibold">{c.help.subtitle}</h2><div className="mt-6 grid grid-cols-2 gap-3"><Link href="/support/contact" className="rounded-2xl bg-white p-4 text-left"><span className="text-xl">✦</span><p className="mt-4 text-xs font-bold">{c.help.chat}</p></Link><a href={CONTACT_PHONE_HREF} className="rounded-2xl bg-white p-4"><span className="text-xl">☎</span><p className="mt-4 text-xs font-bold">{c.help.call}</p></a></div></article></div>
        <p className="mt-8 text-center text-xs text-black/35">{c.demo}</p>
      </section>
    </div></div></main>;
}
