import type { Metadata } from 'next';
import SiteHeader from '@/components/SiteHeader';

export const metadata: Metadata = { title: 'Espace client | SafeR', description: 'Votre tableau de bord SafeR pour piloter la sécurité, suivre vos rendez-vous, paiements, interventions et équipements.' };

export default function ClientPage() {
  return <main className="theme-page client-page min-h-screen bg-[#e9eeea] text-[#0a1814]"><SiteHeader dark={false} />
    <div className="mx-auto max-w-[1440px] px-4 pb-10 pt-4 sm:px-6 lg:px-8"><div className="grid gap-5 lg:grid-cols-[240px_1fr]">
      <aside className="hidden h-[calc(100vh-120px)] rounded-[26px] bg-[#0b1d17] p-5 text-white lg:flex lg:flex-col lg:sticky lg:top-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b8ff3d]">Mon espace</p><div className="mt-6 space-y-1 text-sm"><a className="flex items-center gap-3 rounded-xl bg-white/10 px-3 py-3" href="#"><span>⌂</span>Vue d’ensemble</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#monitoring"><span>◉</span>Monitoring</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#installation"><span>↗</span>Installation</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#payments"><span>▤</span>Factures & paiements</a><a className="flex items-center gap-3 rounded-xl px-3 py-3 text-white/55" href="#support"><span>✦</span>Support</a></div></div><div className="mt-auto rounded-2xl bg-[#b8ff3d] p-4 text-[#07120f]"><p className="text-xs font-bold">Assistance 24/7</p><p className="mt-1 text-xs text-black/50">Un doute, une alerte ?</p><button className="mt-4 w-full rounded-full bg-[#07120f] px-4 py-2.5 text-xs font-bold text-white">Nous contacter</button></div></aside>
      <section>
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-black/40">Dimanche 30 août</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.035em]">Bonsoir, Aïcha.</h1></div><div className="flex items-center gap-3"><button className="rounded-full border border-black/10 bg-white px-4 py-2.5 text-sm font-semibold">Mes documents</button><span className="grid size-11 place-items-center rounded-full bg-[#b8ff3d] text-sm font-bold">AK</span></div></div>
        <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
          <div id="monitoring" className="relative overflow-hidden rounded-[30px] bg-[#0b1d17] p-6 text-white sm:p-8"><div className="absolute -right-10 -top-20 size-72 rounded-full bg-[#b8ff3d]/12 blur-3xl" /><div className="relative flex items-start justify-between"><div><p className="text-xs text-white/40">Résidence Riviera 3</p><h2 className="mt-2 text-2xl font-semibold">Votre maison est protégée.</h2></div><span className="grid size-12 place-items-center rounded-full bg-[#b8ff3d] text-xl text-[#07120f]">✓</span></div><div className="relative mt-12 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">04</p><p className="mt-1 text-xs text-white/35">Accès fermés</p></div><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">07</p><p className="mt-1 text-xs text-white/35">Caméras actives</p></div><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">06</p><p className="mt-1 text-xs text-white/35">Capteurs OK</p></div><div className="rounded-2xl bg-[#b8ff3d] p-4 text-[#07120f]"><p className="text-2xl font-semibold">24/7</p><p className="mt-1 text-xs text-black/40">Veille SafeR</p></div></div><div className="relative mt-5 flex flex-wrap gap-3"><button className="rounded-full bg-white px-5 py-3 text-xs font-bold text-[#07120f]">Armer en mode absence</button><button className="rounded-full border border-white/12 px-5 py-3 text-xs font-bold">Voir les caméras</button><button className="rounded-full border border-white/12 px-5 py-3 text-xs font-bold">Ouvrir le portail</button></div></div>
          <div id="installation" className="rounded-[30px] bg-white p-6"><div className="flex items-start justify-between"><div><p className="text-xs text-black/40">Votre projet</p><h2 className="mt-1 text-xl font-semibold">Extension jardin</h2></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-[10px] font-bold text-amber-700">EN COURS</span></div><div className="mt-7 space-y-5"><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#b8ff3d] text-xs">✓</span><div><p className="text-sm font-semibold">Devis signé</p><p className="mt-1 text-xs text-black/35">26 août · 16h42</p></div></div><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#b8ff3d] text-xs">✓</span><div><p className="text-sm font-semibold">Acompte reçu</p><p className="mt-1 text-xs text-black/35">Mobile Money</p></div></div><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full border-4 border-[#b8ff3d] text-xs" /><div><p className="text-sm font-semibold">Installation planifiée</p><p className="mt-1 text-xs text-black/35">Mardi 1 septembre · 10h–12h</p></div></div><div className="flex gap-3 opacity-35"><span className="grid size-7 shrink-0 place-items-center rounded-full border border-black/20 text-xs" /><div><p className="text-sm font-semibold">Mise en service</p><p className="mt-1 text-xs">À venir</p></div></div></div><button className="mt-6 w-full rounded-full border border-black/10 px-4 py-3 text-xs font-bold">Modifier le rendez-vous</button></div>
        </div>
        <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">
          <article className="rounded-[26px] bg-white p-6"><div className="flex justify-between"><div><p className="text-xs text-black/40">Dernier événement</p><h3 className="mt-1 font-semibold">Portail principal</h3></div><span className="grid size-10 place-items-center rounded-full bg-[#e9eeea]">↗</span></div><div className="mt-8 border-l-2 border-[#b8ff3d] pl-4"><p className="text-sm font-semibold">Ouverture autorisée</p><p className="mt-1 text-xs text-black/35">Aujourd’hui · 18h12 · Utilisateur : Vous</p></div><button className="mt-6 text-xs font-bold underline underline-offset-4">Voir le journal complet</button></article>
          <article id="payments" className="rounded-[26px] bg-white p-6"><div className="flex justify-between"><div><p className="text-xs text-black/40">Prochaine échéance</p><h3 className="mt-1 font-semibold">Abonnement Sérénité</h3></div><span className="grid size-10 place-items-center rounded-full bg-[#e9eeea]">▤</span></div><p className="mt-8 text-3xl font-semibold">34 900 <span className="text-sm">FCFA</span></p><p className="mt-1 text-xs text-black/35">Le 5 septembre · Mobile Money</p><button className="mt-6 rounded-full border border-black/10 px-4 py-2.5 text-xs font-bold">Gérer le paiement</button></article>
          <article id="support" className="rounded-[26px] bg-[#b8ff3d] p-6 md:col-span-2 xl:col-span-1"><div className="flex justify-between"><div><p className="text-xs text-black/40">Maintenance préventive</p><h3 className="mt-1 font-semibold">Contrôle recommandé</h3></div><span className="grid size-10 place-items-center rounded-full bg-white">✦</span></div><p className="mt-8 text-sm leading-6 text-black/55">Votre dernière vérification date de 11 mois. Réservez un passage avant la saison des pluies.</p><button className="mt-6 rounded-full bg-[#07120f] px-4 py-2.5 text-xs font-bold text-white">Choisir un créneau</button></article>
        </div>
        <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-[30px] bg-white p-6 sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#669516]">Votre système peut aller plus loin</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">Sécurisez aussi votre dépendance.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-black/45">Ajoutez une caméra extérieure et un détecteur d’ouverture à votre installation actuelle.</p></div><span className="grid size-14 place-items-center rounded-2xl bg-[#e9eeea] text-2xl">◉</span></div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button className="rounded-full bg-[#0b1d17] px-5 py-3 text-xs font-bold text-white">Ajouter à mon système</button><button className="rounded-full border border-black/10 px-5 py-3 text-xs font-bold">Plus tard</button></div></article><article className="rounded-[30px] border border-black/8 p-6"><p className="text-xs text-black/40">Besoin d’assistance ?</p><h2 className="mt-2 text-xl font-semibold">Nous sommes là, 24/7.</h2><div className="mt-6 grid grid-cols-2 gap-3"><button className="rounded-2xl bg-white p-4 text-left"><span className="text-xl">✦</span><p className="mt-4 text-xs font-bold">Chat SafeR</p></button><a href="tel:+2250000000000" className="rounded-2xl bg-white p-4"><span className="text-xl">☎</span><p className="mt-4 text-xs font-bold">Appeler</p></a></div></article></div>
        <p className="mt-8 text-center text-xs text-black/35">Espace client de démonstration. Les données affichées sont fictives.</p>
      </section>
    </div></div></main>;
}
