import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';

export const metadata: Metadata = { title: 'Maintenance de votre système', description: 'Entretien préventif, assistance et maintenance des systèmes SafeR en Côte d’Ivoire.' };

export default function MaintenancePage() {
  return <main className="theme-page bg-[#f3f5fb] text-black">
    <section className="bg-black text-white"><SiteHeader /><div className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><nav className="text-xs text-white/45"><Link href="/support">Support</Link> / Maintenance</nav><p data-i18n="support.maintenance" className="mt-10 text-xs font-bold uppercase tracking-[.16em] text-[#52c6ff]">Maintenance & entretien</p><h1 className="mt-5 text-5xl font-light leading-[1] tracking-[-.05em] sm:text-6xl">Votre système reste prêt. Toute l’année.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/60">Un programme préventif adapté au site, aux équipements et à leur niveau de criticité.</p></div><div className="media-grade relative min-h-[460px] overflow-hidden rounded-[34px]"><img src="https://images.pexels.com/photos/4481326/pexels-photo-4481326.jpeg?auto=compress&dpr=1&h=1000&w=1400" alt="Maintenance technique" className="absolute inset-0 h-full w-full object-cover" /></div></div></section>
    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-7 lg:grid-cols-2 lg:items-end"><div><p className="eyebrow">Programme préventif</p><h2 className="section-title mt-5">Contrôler. Tester. Anticiper.</h2></div><p className="max-w-xl leading-7 text-black/50 lg:ml-auto">La fréquence dépend de l’environnement, de l’exposition et du niveau de service. Votre espace client centralise les rapports et prochaines échéances.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['01','Inspection','État visuel, fixation, alimentation et connectivité.'],['02','Essais','Capteurs, sirènes, vidéo, scénarios et protocoles.'],['03','Optimisation','Réglages, nettoyage et mises à jour applicables.'],['04','Rapport','Actions réalisées, anomalies et recommandations.']].map(([n,title,text]) => <article key={n} className="rounded-[26px] border border-black/8 bg-white p-6"><span className="text-sm font-semibold text-[#4556f5]">{n}</span><h3 className="mt-14 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-black/50">{text}</p></article>)}</div></div></section>
    <section className="bg-[#52c6ff] px-5 py-20 text-black lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-black/45">Planifier une visite</p><h2 className="mt-4 text-4xl font-light">Choisissez votre créneau dans l’espace client.</h2></div><Link href="/espace-client#support" className="rounded-full bg-black px-7 py-4 text-center text-sm font-bold text-white">Planifier la maintenance</Link></div></section>
    <SiteFooter />
  </main>;
}
